### ISSUE TITLE
Images - Amélioration de la fonctionnalité Highlight

### ISSUE THREAD

**Issue by PhilippeVay** [arneoio/rgaa-checker#8]
## Description du problème

La fonctionnalité _highlight_ tente de distinguer les éléments audités par un critère du reste du contenu en ajoutant une opacité de 0.2 au reste du contenu mais pas aux éléments audités (ex: "les images" ou "les tableaux").
Pour les images, certains nœuds texte ne sont pas correctement estompés : les nœuds texte ayant un parent commun avec une image ne deviennent pas translucides et il n'est pas possible de leur ajouter une opacité à moins de les encapsuler dans un span (pas une bonne idée quand on ne connait rien de la page) ou d'également rendre translucide l'image en l'ajoutant sur le parent.
Sur https://www.alsacreations.fr, les 4 images HTML5, etc sont estompées mais pas les p ou li ayant un span avec du texte.

> ![image](https://github.com/arneoio/rgaa-checker/assets/534395/06cdc4e3-b173-42dd-a68d-a43cbd470ea1)

## Pistes...

Après avoir passé une journée à développer une solution JS, SVG et `mask-image`, je viens d'en (re)trouver une autre en pur CSS ou presque...  
On peut en effet :
* passer tout le texte en `color: rgba(0, 0, 0, 0.2)` 👻 (et supprimer fonds, bordures, etc)
* distinguer les "images" en leur ajoutant outline et bordure (prévoir le cas `overflow: hidden`)
* ne pas se préoccuper de la spécificité en dégainant `@layer` et `!important` 🌋

Pour la spécificité, j'avais remonté chez ffoodd ce que permettait [`@layer` (snippet d'exemple et lien vers l'article de référence de bram.us)](https://github.com/ffoodd/a11y.css-webextension/issues/20#issuecomment-1565393944) avec 1 seule limitation bien rare.[^1]

## Solution proposée (CSS et JS) ⬇️ 

<details><summary>Placer le at-layer le plus tôt possible (JS)</summary>

Placer notre `@layer` nommé le plus tôt possible dans la page. Pas essentiel à moins de devoir écraser d'autres styles eux aussi dans un `@layer` et avec `!important`, ça fait beaucoup de conditions...

```js
(function () {
  let e = document.createElement("style");
  e.prepend("@layer rgaac-hl-img;");
  document.head.querySelector("title").after(e);
})()
```
</details>

<details><summary>Highlight les images d'une page (CSS)</summary>

```css
/* Highlight "images" in a page */
@layer rgaac-hl-img {
  * {
    filter: none !important; /* Images may have weird filters */
  }

  /* Everything except images */
  *:not(:where(
    img,
    [role="img"],
    area,
    svg,
    :where(input, object, embed)[type="image"])) {
    color: rgba(0, 0, 0, 0.2) !important;
    background: transparent !important;
    border-color: transparent !important;
    outline-color: transparent !important;
    text-shadow: none !important;
  }

  /* All type of images and then SVG. TODO: <canvas> */
  :where(
    img, /* includes [ismap] */
    [role="img"],
    area,
    :where(input, object, embed)[type="image"]) {
      outline: 2px dashed green !important;
      outline-offset: -2px !important;
      box-shadow:
        4px 0 0 -2px darkred,
        0 4px 0 -2px blue !important;
  }
  
  svg {
    border: 3px solid green !important;
    outline: 3px dashed white !important;
    outline-offset: -3px !important;
  }

  /* Pseudo-elements are not valid in the selector list for :is() or :where() */
  *::before,
  *::after {
    color: rgba(0, 0, 0, 0.2) !important;
    background: transparent !important;
    border-color: transparent !important;
    outline-color: transparent !important;
    text-shadow: none !important;
  }

  /* Detect and flag : inline styles with !important are more specific
      than any @layer :( (for now, all properties are selected even if commented) */
  body:has( [style*="!important"] )::before {
    content: "Page contains inline style with !important" !important;
    position: relative !important;
    z-index: 987654 !important;
    display: block !important;
    margin-bottom: 1rem !important;
    padding: 1rem !important;
    color: white !important;
    background: darkred !important;
  }
}
```
</details> 

## Tests

URLs de test :

* https://www.vigicrues.gouv.fr/ pour sa map area "responsive"
* https://gimb.public.lu/fr.html Image-bandeau sous le titre principal. Utilise `::before` et `::after` pour des images de fond (à gauche de titres sur 3 colonnes) et couleur de fond (footer)
* https://dataemploi.pole-emploi.fr/accueil Titre avec `text-shadow`, carte avec multiples images. Rien de simple à faire pour le bouton de retour en haut car couleur de fond portée par un parent
* https://help.ticketmaster.fr/hc/fr Icônes ZD ayant `filter` _spécial_

## Vu ailleurs

Du côté de la concurrence 🕵️‍♂️ :

* Entre temps j'ai décompilé le bookmarklet [_Isolate images_](https://a11y-tools.com/bookmarklets/#isolateimages) d'A11Y-Tools (Lloydi) et il a des différences (code lisible dans un [gist](https://gist.github.com/PhilippeVay/d73ad273aac1a8a7eeed0b1720c268fe)).  
En JS, il cible chaque élément qui n'est pas une image et applique `el.style.color="transparent";`, etc Le texte est réduit à une taille de 1px aussi, pour ne garder que les images.  
Sur les images, pour les distinguer, un outline de 10px (offset de -10px) noir est ajouté.
* ARC Toolkit : pas testable ce WE

[^1]: Cela écrase bien aussi les styles _inline_ mais je viens de me rendre compte (ou bien j'avais oublié depuis) qu'un style _inline_ avec `!important` aura toujours plus de spécificité que n'importe quel `@layer`. Mmh si j'en ai rencontré une fois, c'était il y a 10 ans dans du GG Maps _embedded_ ou du temps d'IE6 et ça a disparu il y a bien longtemps. Bref c'est plus que rare et ça se détecte en CSS.
